### ISSUE TITLE
exception: {:type :jepsen.db/setup-failed, :msg :await-open-timeout, :node "n4"} 

### ISSUE THREAD

**Issue by mengrj** [scylladb/jepsen#13]
Trying to use Jepsen to test the latest version of Scylladb (e.g., v5.0.0). However, I always get the following error during setup and have no idea how to fix it: 

Begin with this warning:
```
===== Using optimized driver!!! =====
INFO [2022-08-02 13:09:29,858] jepsen node n2 - scylla.client n2 not yet available, retrying
```
And finally, get this error: 
```
ERROR [2022-08-02 13:10:14,676] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
clojure.lang.ExceptionInfo: throw+: {:type :jepsen.db/setup-failed, :msg :await-open-timeout, :node "n4"}
```
Could you give some suggestions to fix this error?

**Comment by kostja** [comment]
Look at scylla boot logs?
