### ISSUE TITLE
jepsen long runs hang from time to time

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/jepsen#4]
HEAD: b19c5bb088c22c9420d885ea2da6896e68c7e0a5
AWS Instance: c3.8xlarge built from ami-dbd320bb
## Decription

When running `lein test :batch :set :map` one out of two runs in average hangs without any obvious reason.

gdb shows that java process is stuck on pthread_join() and the thread that it waits for is stuck waiting for a condvar.

**Comment by vladzcloudius** [comment]
I suspect there is some bug in the way workers threads are waited for. Needs more code drilling.

**Comment by kostja** [comment]
We've moved on to a rebased version.
